sudo: required
dist: xenial
notifications:
  email: false
services:
- docker
language: java
jdk:
- openjdk11
env:
  matrix:
  - DOCKER_VERSION=17.03.1~ce DOCKER_CE=1
  - DOCKER_VERSION=17.06.2~ce DOCKER_CE=1
  - DOCKER_VERSION=17.09.1~ce DOCKER_CE=1
  - DOCKER_VERSION=17.12.1~ce DOCKER_CE=1 UPLOAD_SONATYPE=1
  global:
  - secure: f4AXPgVRNoPXeYTmr9awjFqkWYNbb3fi3LMPppAL22mPcRPiNOiikdBaYrdIcytK5iaRzcZ24CbGUGUJaoWPenKqo6LSinAY1HEhQnCdbEN/o2iXtXeyivasLItEiw+KF0BJD5LhwlVEnWKLzRLaHbPv+LA3NgJ7dPsW0g99UKqp/W35/67xCyuP2cUBpS2j2kKFrznqg/1dIr93JMxajdfF1Zy/3JWTAO4wyOKmnK+dWyDfAJfUcq9WVEJcBYgmFFjNwQrj36v2v9kenV7ZOkLV9nbcSVyI46q7TNANv1O89HlK+Zjv5kQno1WsaOiqDlhHt5PWGMJHFVnmDa2VxPv2iGeJ4RdtIgoemd6E9C6BzTOUtBXHRwFCgSlPIAqj1EaZwLyQigOoPY0NWpBAHKp1YhandBBMG9CUUH/4o5sWWuCN6GR3iHDqwNPleXpGC8on995re58NbFxUZvwgXU7PFxj3XFw4QxbZdQ4+hCKPP/pzpn4dmpT98wZeAk9souPmOCy7hmXs+EzHa6b5uU1V+R/JdlFvjS8FpFXvA4m2CSxJWX4jm62itKYVFhrJezGdYry0mVnHFLzsnSRxIFx3uXoNShB/pr8+TT+8iGeOyUXLZhRw8mVwTy9kx1AByyMJX0nFrVJoY9l0nSc3I3Tmifjxcd1KEoIiPwGM9bw=
  - secure: deCfBks2+Mgw6eXXaBiv/3emq3yaaAXSyXHz0xEcDFLhosKbfWfU7zVjSjgNFqPRM2/vPtk72RCS1Vo5G6odKHu9W55aCjdiWmdZ3SStx7p6yiBd5KLBM4P+KQ6n2FtuwbIS5u6nukiuXJ1EISPIrPDjPWyiY+P7d4TbhD1ncvPmrsmba7LdM0zbR5el5ngBIzMp2PutUNXK2u3k+QrCiBDWqROwNwJtUzORspH2nYzKHzVse2K71mkS6YE1rssb9AAiqX4OfcxI+ZeYACAUeRd2IKRz8evawTupK5EhLCS/3XsMCB6l9o55SsfZDl4VxxKUHrddcJX8TKYalK2e5kQADYvK08Q5E0xu0SfsG3+C+RsBP8q9iOsOH7J/0XUAcYbZt9ZOCjO3M6lNbheN37Fq2VXKlFgaTY/1CeXK9JdlQDpvHDjAwc3wvYM2y/1/WdYdpR7x3y8amQSh+RDpfF01PVanNwdKj9Fp+W4Jol6+dgw7FVkCdWwfvcRs3/O57iqtYpon1Ug0WQKy/8VhtWYqwejYaqWlrDg/0tstqAsfk1hOwgad5smQlNKb7zUqsNURJuD7XVlcKXxSGlDfb9cT0wrUQZA04T+CN1u2XN1wevfUFkoVu9aF1gUB0ChLo8EEk/Z2OwX+SsT02ODAtV64A180jK/EqksqZFPG3Go=
  - secure: 0RNwMWSnPpUohA8vJY4wn39ZQ/+sYlVqFw05XaTWg5yiSjb4b5ke6htknY/S9njnjMQiigEDuP82omX0zMugE/sssvFZYw4MQ1G9WLG1LlJZ5NhydnUIeCreNT4r805qjqSr3Bgv3jzJSx+fscEs5n6rMvZDwk2N/zmD5e+81YTMs68Auukt7PcCbOr7MflzGqMlnVbBYzxRN45bW13oKhAC6Iz5+UgjkahrSwtYmMs3qlK6zoTr6mrPrLJ+3lVFSArsxcfdKBIQ3sNkIuCYR1Jfs+uOto26yVoOGUziTSHSJ+0YA+HfDk96+hHN1oP4O3w+ba+qzo4X2EhJbyOlieM2qK+/q2XHP9BbSMTf5PaDbbU4owxlVWDK2jOeys1dhYVWWFk3Yji5Uvzhci8Y01PPUgogrpXymXule3T7vAlV60CJbPhm7JIJE2BwJBdGxAG0n8BTsNIuhGCI23RnbldhaiuYRFDGMNEmYXRPm9R/t4N3U4eClam7Ka+G0wCDvGzkPwTiVF/LNquEkOIIMWUt1VVSZN2iy4JRdVcozMeeOqGcTU8n/vH0yAe5Kw5pUoaXxuIuGLhWOhiLHjqFQyNJgTlWgYjJwqywcyjjCJk06zRTAPNNJkxkZpuvGtNHyT1oIIXMmTqH4yDs2fqyx768p7DLKtdDpFO6I1vT2WY=
  - secure: txwtxGvjOwb4L4ckdAvmjTjfR7ySMiS+aMN4aj9HVwZrYp9WTzGYZkt84xvCdHGCNW1Awm4MvRuDooHXmelOUE717ACpSJqnNOeZZxAE1QXLqD35Dun487c6ObIB1NtodJ0j+KL6aNnBX9JTej6ehU1k02jnEGIOio0KxDOpi3LugKUE8xxeUvnCvb4rILs5BLNLbt87igRLiGWHIuGkSqgSQQKuVrNz1v1W32RysAMzAiKXMQRuGc1bli1yqdwycbiFesgRVpN58mvROtA/US6EjbfYjNaYX72Hgx2Q1vKuGzLToJ2nL1TsBiFmKsgDRpPuZ4WSNqncCrgNMaI+cP7x0cFAIPYQ/Gao/+T1kZbU53Y9jAht/QCIUXncZRcWCLYZSJsy+EVAvMgmSYYJiTMtaS8/i1t+fnkfCNSCvFgHQHohXp/fY5Sgke1WujDwhXEQYK/iCzKURThjY9mWbO6LC9pE/Z98vP8qSRF6u6zmhLLAe3z2RpGgc/s6I2JGIZbgn0Pod5Hos1CAWSEyft8mT0sQyUrZVcTCCdhmQQS9o7Y7dFHh+O5gXcSs9fhDM8kIedRK4r8rxu9kTbGP7HIuTmVwISqzURaz0/oK1p/8mtWQScOb9I+QGozf24YC/m8grW8uZqQuk33zS+eTR9odVWU20rd8rZ5pBxopEJo=
before_install:
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then openssl aes-256-cbc -K $encrypted_7a129298b602_key -iv $encrypted_7a129298b602_iv
  -in secret.asc.enc -out secret.asc -d; fi
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then gpg --import secret.asc; fi
- dpkg -l | grep docker
- "./.travis.sh install_docker"
- docker version
- docker info
script:
- if [ $TRAVIS_PULL_REQUEST == "false" -a x$UPLOAD_SONATYPE == x1 ]; then mvn --settings
  sonatype-settings.xml -Pdeploy-artifacts clean deploy -Dsurefire.rerunFailingTestsCount=1;
  fi
- if [ $TRAVIS_PULL_REQUEST != "false" -o x$UPLOAD_SONATYPE != x1 ]; then mvn clean
  test -Dsurefire.rerunFailingTestsCount=1; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
after_failure:
- "./.travis.sh dump_docker_config"
branches:
  only:
  - master
  - /^release-\d+\.\d+\.\d+$/
cache:
  directories:
    - $HOME/.m2
